### ISSUE TITLE
UIApplicationAttribute method not found

### ISSUE THREAD

**Issue by xmerta00** [Kentico/xperience-by-kentico-algolia#14]
### Brief bug description

The constructor of the `UIApplicationAttribute` class has been changed and cannot be called from the NuGet package: https://github.com/Kentico/xperience-by-kentico-algolia/blob/7a7a80cff942390c3c74570d1cf7c1296ec1bdb2/src/CmsRegistrations.cs#L22

### Test environment

- Xperience by Kentico (26.0.2) 
- Kentico.Xperience.Algolia (1.0.0) 

### Additional context

stack trace of the error:
System.MissingMethodException: Method not found: 'Void Kentico.Xperience.Admin.Base.UIApplicationAttribute..ctor(System.Type, System.String, System.String, System.String, System.String, System.String)'.
1>   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
1>   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
1>   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
1>   at System.RuntimeType.GetMethodBase(RuntimeModule scope, Int32 typeMetadataToken)
1>   at System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope, MetadataToken caCtorToken, ConstArray& blob)
1>   at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
1>   at CMS.Core.AssemblyDiscovery.IsAssemblyDiscoverable(Assembly assembly)
1>   at CMS.Core.AssemblyDiscovery.AddOnlyDiscoverableAssembly(ICollection`1 assemblies, Dictionary`2 preloadedAssemblies, AssemblyName assemblyName, String filePath)
1>   at CMS.Core.AssemblyDiscovery.ExecuteGetAssemblies(Boolean onlyDiscoverable)
1>   at CMS.Core.AssemblyDiscovery.get_DiscoverableAssemblies()
1>   at CMS.Core.AssemblyDiscovery.GetAssemblies(Boolean discoverableOnly)
1>   at CMS.Core.AssemblyDiscoveryHelper.GetAssemblies(Boolean discoverableOnly)
1>   at CMS.Core.ModuleDiscovery.GetModules()
1>   at CMS.Core.ModuleEntryManager.GetDiscoverableModules()
1>   at CMS.Core.ModuleEntryManager.ModuleCollectionsInitialization()
1>   at CMS.Core.ModuleEntryManager.PreInit()
1>   at CMS.Core.AppCore.PreInit()
1>   at CMS.DataEngine.CMSApplication.PreInit(Boolean initializeContainer)
1>   at Kentico.Web.Mvc.IServiceCollectionExtensions.PreInitCmsApplication()
1>   at Kentico.Web.Mvc.IServiceCollectionExtensions.AddKenticoCore(IServiceCollection services)
1>   at Kentico.Web.Mvc.StartupExtensions.AddKentico(IServiceCollection services, Action`1 featuresBuilder)
1>   at Program.<Main>$(String[] args) in C:\repos\...

**Comment by ondrejhenek** [comment]
Thanks for submitting this bug! We are looking into it and will come back to you in a few days.

**Comment by ondrejhenek** [comment]
Fixed by #16. We will be faster next time.
