### ISSUE TITLE
Add support for "Content items" fields

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/xperience-by-kentico-algolia#17]
### Motivation

Previously, our Dancing Goat sample site used the "Media files" data type for fields like `Article.ArticleTeaser`. These fields are supported by the `MediaUrls` attribute which outputs a list of absolute URLs to the selected media files.

With the release of the Content Hub, the ArticleTeaser field now uses the "Content items" data type, and our [sample code](https://github.com/Kentico/xperience-by-kentico-algolia#gear-creating-and-registering-an-algolia-index) no longer functions.

### Proposed solution

A new attribute named something like `ContentItemUrls` which generates absolute URLs to the content items. Or, the functionality of `MediaUrls` and this new attribute could be combined into a single attribute which handles both data types.

**Comment by ondrejhenek** [comment]
Thanks for the feedback. As this is not an urgent issue, we are putting this idea into our internal backlog and will come back to it probably in a few months.
