### ISSUE TITLE
Algolia index detail error in administration + rebuild not working

### ISSUE THREAD

**Issue by denny101603** [Kentico/xperience-by-kentico-algolia#18]
### Brief bug description

- I tried to create Algolia index, following readme in this repo. In administration I see the algolia application with the created index. When I click on the index a detail page should open (which I see for a few miliseconds), but then I get error (Something went wrong!). No error in the event log, find attached console log from Chrome. [consoleLog.txt](https://github.com/Kentico/xperience-by-kentico-algolia/files/11551363/consoleLog.txt)

- Other problem is that the index is empty. When I click on the rebuild button (in list of indexes, Kentico administration), I see green notification about rebuild in progress, but according to Algolia dashboard (where I see the created index), no records are added.

### Repro steps

1. Follow sections "Installation" and "Creating and registering an Algolia index" from readme
2. Run project, go to Kentico administration, go to "Algolia" application, click on the created index

### Test environment

- Xperience by Kentico (26.2.0)
- Kentico.Xperience.Algolia (2.0.0)

### Screenshots

![image](https://github.com/Kentico/xperience-by-kentico-algolia/assets/43618398/7e8b152f-5bcd-4f15-9327-757f6c40e679)
![image](https://github.com/Kentico/xperience-by-kentico-algolia/assets/43618398/ab9e1762-7b6e-45e8-a0b4-390806d363dc)

**Comment by ondrejhenek** [comment]
Hi, the first issue in admin UI "Something went wrong!" has been resolved: https://www.nuget.org/packages/Kentico.Xperience.Algolia Please, update your package to a version 2.0.1

The second issue could not be replicated. Could you, please, include API log regarding that index directly from Algolia?

Also, I am closing this issue to keep things in order - one issue per one problem. It's easier to track things. So, please if the second problem persists, **create a new issue and include Algolia API log**. We will jump on it ASAP. Thank you!
