### ISSUE TITLE
Rebuild not working

### ISSUE THREAD

**Issue by denny101603** [Kentico/xperience-by-kentico-algolia#20]
### Brief bug description

I created new Algolia index, but it is empty.  When I click on the rebuild button (in list of indexes, Kentico administration), I see green notification about rebuild in progress, but according to Algolia dashboard (where I see the created index), no records are added. 

No errors in event log. For each rebuild try, these two request are in the Algolia "Search API logs":

[AlgoliaLog_Item1.txt](https://github.com/Kentico/xperience-by-kentico-algolia/files/11573189/AlgoliaLog_Item1.txt)
[AlgoliaLog_Item2.txt](https://github.com/Kentico/xperience-by-kentico-algolia/files/11573191/AlgoliaLog_Item2.txt)

### Repro steps

1. Follow sections "Installation" and "Creating and registering an Algolia index" from readme
2. Run project, go to Kentico administration, go to "Algolia" application, click on "build index" button

### Expected behavior
Records should be added to the index (corresponding with the published pages of selected content type)

### Test environment

- Xperience by Kentico (26.2.0)
- Kentico.Xperience.Algolia (2.0.1)

### Screenshots
Screenshots of search model, service registration and existing pages:
![image](https://github.com/Kentico/xperience-by-kentico-algolia/assets/43618398/de6172ff-1bc8-4788-b1ab-7c7dd7fa7ad0)
![image](https://github.com/Kentico/xperience-by-kentico-algolia/assets/43618398/6936e123-aede-499b-b1d4-3be88bcf0718)
![image](https://github.com/Kentico/xperience-by-kentico-algolia/assets/43618398/613a89f0-9020-495f-9d58-e97a611ce03d)

The NewsDetail page type has properties "Title" and "Perex" besides others.

**Comment by Lahvac** [comment]
@denny101603 thanks for your reply. I was able to reproduce the error using 'de-DE' culture in DEV environment. 

The issue will be fixed by my pull request #21
